"""Initialisation de la nouvelle base de données

Revision ID: 114de8ad976a
Revises: 
Create Date: 2025-06-28 04:30:23.663850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114de8ad976a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mywitti_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('categ_points', sa.Integer(), nullable=True),
    sa.Column('recompense_point', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('min_jetons', sa.BigInteger(), nullable=True),
    sa.Column('nb_jours', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mywitti_comptes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(), nullable=True),
    sa.Column('agence', sa.String(), nullable=True),
    sa.Column('numero_compte', sa.String(), nullable=True),
    sa.Column('libelle', sa.String(), nullable=True),
    sa.Column('date_ouverture_compte', sa.Date(), nullable=True),
    sa.Column('working_balance', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mywitti_user_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultat_criteria',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('criteria_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveys',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blacklist_jti'), ['jti'], unique=True)

    op.create_table('mywitti_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('recompense_image', sa.Text(), nullable=True),
    sa.Column('jetons', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['mywitti_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mywitti_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('user_type_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_type_id'], ['mywitti_user_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('survey_options',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('survey_id', sa.BigInteger(), nullable=False),
    sa.Column('option_text', sa.String(length=50), nullable=False),
    sa.Column('option_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mywitti_client',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('customer_code', sa.String(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('jetons', sa.BigInteger(), nullable=True),
    sa.Column('date_ouverture', sa.String(), nullable=True),
    sa.Column('nombre_jours', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['mywitti_category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['mywitti_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mywitti_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['mywitti_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=False),
    sa.Column('referred_email', sa.String(length=255), nullable=False),
    sa.Column('referral_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referrer_id'], ['mywitti_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_table('support_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['mywitti_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mywitti_client_jetons_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('date_jour', sa.Date(), nullable=True),
    sa.Column('solde_jetons', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['mywitti_client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mywitti_client_palier_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('palier', sa.String(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['mywitti_client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mywitti_jetons_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('montant', sa.Integer(), nullable=True),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.Column('date_transaction', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['mywitti_client.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['mywitti_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mywitti_lots_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('date_reclamation', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['mywitti_client.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['mywitti_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mywitti_lots_favoris',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('date_ajout', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['mywitti_client.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['mywitti_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultat_clientarecompense',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['mywitti_category.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['mywitti_client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['mywitti_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultat_point',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('notation', sa.String(length=255), nullable=False),
    sa.Column('jeton', sa.Integer(), nullable=False),
    sa.Column('mois', sa.String(length=50), nullable=False),
    sa.Column('montant', sa.BigInteger(), nullable=False),
    sa.Column('date_notes', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['mywitti_client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultat_total',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['mywitti_client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_responses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('survey_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('option_id', sa.BigInteger(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['mywitti_client.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['survey_options.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['mywitti_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_responses')
    op.drop_table('resultat_total')
    op.drop_table('resultat_point')
    op.drop_table('resultat_clientarecompense')
    op.drop_table('mywitti_lots_favoris')
    op.drop_table('mywitti_lots_claims')
    op.drop_table('mywitti_jetons_transactions')
    op.drop_table('mywitti_client_palier_history')
    op.drop_table('mywitti_client_jetons_daily')
    op.drop_table('support_requests')
    op.drop_table('referrals')
    op.drop_table('mywitti_notification')
    op.drop_table('mywitti_client')
    op.drop_table('survey_options')
    op.drop_table('mywitti_users')
    op.drop_table('mywitti_lots')
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blacklist_jti'))

    op.drop_table('token_blacklist')
    op.drop_table('surveys')
    op.drop_table('resultat_criteria')
    op.drop_table('page_visit')
    op.drop_table('mywitti_user_type')
    op.drop_table('mywitti_comptes')
    op.drop_table('mywitti_category')
    op.drop_table('faqs')
    # ### end Alembic commands ###
