"""migration publicité

Revision ID: 76a92ea6abbe
Revises: 90954b12098b
Create Date: 2025-07-07 22:50:28.639253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a92ea6abbe'
down_revision = '90954b12098b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mywitti_advertisements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['mywitti_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mywitti_advertisements', schema=None) as batch_op:
        batch_op.create_index('idx_advertisements_active', ['is_active'], unique=False)
        batch_op.create_index('idx_advertisements_active_country', ['is_active', 'country'], unique=False)
        batch_op.create_index('idx_advertisements_country', ['country'], unique=False)
        batch_op.create_index('idx_advertisements_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mywitti_advertisements', schema=None) as batch_op:
        batch_op.drop_index('idx_advertisements_created_at')
        batch_op.drop_index('idx_advertisements_country')
        batch_op.drop_index('idx_advertisements_active_country')
        batch_op.drop_index('idx_advertisements_active')

    op.drop_table('mywitti_advertisements')
    # ### end Alembic commands ###
